# Generated by Django 4.0.4 on 2022-05-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('acronimo', models.CharField(max_length=10)),
                ('ano_criacao', models.IntegerField(default=1)),
                ('criador', models.CharField(default='', max_length=50)),
                ('logotipo', models.IntegerField(default=1)),
                ('link', models.CharField(max_length=500)),
                ('descricao', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PontuacaoQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pontuacao', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='projeto',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='ects',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='ranking',
            field=models.IntegerField(),
        ),
    ]
