# Generated by Django 4.0.4 on 2022-05-31 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_linguagem_pontuacaoquizz_pessoa_email_projeto_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='descricao',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='prof_teorica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa'),
        ),
    ]
