# Generated by Django 4.0.4 on 2022-05-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_picture_cadeira_descricao_cadeira_prof_teorica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
    ]
