# Generated by Django 4.0.4 on 2022-05-31 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_cadeira_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='prof_pratica',
            field=models.ManyToManyField(default=1, related_name='cadeiras', to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='descricao',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='prof_teorica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa'),
        ),
    ]
