# Generated by Django 4.0.4 on 2022-06-02 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_cadeira_link_cadeira_prof_pratica_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='link',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='projeto',
            name='ano',
            field=models.IntegerField(default=2010),
        ),
        migrations.AddField(
            model_name='projeto',
            name='cadeira',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.cadeira'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='link_github',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projeto',
            name='link_youtube',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projeto',
            name='logotipo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(default=1, related_name='pessoas', to='portfolio.pessoa'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(default=1, related_name='tecnologias', to='portfolio.linguagem'),
        ),
        migrations.AlterField(
            model_name='linguagem',
            name='logotipo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='TrabalhoFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('resumo', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('link_github', models.CharField(max_length=500)),
                ('link_youtube', models.CharField(max_length=500)),
                ('orientadores', models.ManyToManyField(default=1, related_name='orientadores', to='portfolio.pessoa')),
            ],
        ),
    ]
