# Generated by Django 4.0.4 on 2022-06-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_link_projeto_descricao_projeto_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linguagem',
            name='criador',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='linguagem',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
