# Generated by Django 4.0.4 on 2022-06-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_linguagem_criador_alter_linguagem_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('link', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
