# Generated by Django 4.0.4 on 2022-06-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='linguagem',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='link_github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='link_youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='trabalhofc',
            name='link_github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='trabalhofc',
            name='link_youtube',
            field=models.URLField(blank=True),
        ),
    ]
