# Generated by Django 4.0.4 on 2022-06-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_blog_link_alter_cadeira_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='linguagem',
            name='ano_criacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='linguagem',
            name='link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='link_github',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='link_youtube',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trabalhofc',
            name='link_github',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='trabalhofc',
            name='link_youtube',
            field=models.CharField(max_length=500),
        ),
    ]
