# Generated by Django 4.0.4 on 2022-06-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_blog_link_alter_cadeira_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=50)),
                ('ano_Inicio', models.IntegerField()),
                ('ano_Fim', models.IntegerField()),
                ('grau', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=10)),
                ('qualificacao', models.CharField(max_length=10)),
                ('classificacao', models.CharField(max_length=50)),
            ],
        ),
    ]
