# Generated by Django 4.0.4 on 2022-06-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_questionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trabalhofc',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trabalhofc',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trabalhofc',
            name='resumo',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='trabalhofc',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
