# Generated by Django 4.0.4 on 2022-06-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_blog_autor_alter_blog_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhofc',
            name='orientadores',
            field=models.ManyToManyField(related_name='orientadores', to='portfolio.pessoa'),
        ),
    ]
